version: "3"

services: 
        baza:
                image: postgres
                volumes: 
                        - dane_bazy:/var/lib/postgresql/data
                environment:
                        POSTGRES_USER: ja
                        POSTGRES_DB: mojabaza
                        POSTGRES_PASSWORD: mojehaslo
                        
                networks:
                        - baza-net

        my_app:
                build:
                        context: ./mysite
                        dockerfile: Dockerfile
                image: django_img

                networks:
                        - baza-net
                        - app-net
              
                depends_on:
                        - baza

        gateway:
                image: nginx
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf:ro
                depends_on:
                        - my_app
                networks:
                        - app-net
                ports:
                        - 8080:8080
                          
networks:
        baza-net:
        app-net: 
volumes:
        dane_bazy:


