version: "3"

services: 
        baza:
                image: postgres
                volumes: 
                        - dane_bazy:/var/lib/postgresql/data
                environment:
                        POSTGRES_USER: ja
                        POSTGRES_DB: mojabaza
                        POSTGRES_PASSWORD: mojehaslo
                        
                networks:
                        - baza-net

        my_app:
                build:
                        context: ./mysite
                        dockerfile: Dockerfile
                image: django_img

                networks:
                        - baza-net
                ports:
                        - 8080:8080
                depends_on:
                        - baza


networks:
        baza-net:
    
volumes:
        dane_bazy:


