version: "3"

services: 
        baza:
                image: postgres
                volumes: 
                        - dane_bazy:/var/lib/postgresql/data
                environment:
                        POSTGRES_USER: ja
                        POSTGRES_DB: mojabaza
                        POSTGRES_PASSWORD: mojehaslo
                networks:
                        - baza-net
        panel:
                image: adminer
                networks:
                        - baza-net
                ports:
                        - 8008:8080
networks:
        baza-net:
    
volumes:
        dane_bazy:


